DROP TABLE IF EXISTS Language;
CREATE TABLE Language (
  locale TEXT NOT NULL PRIMARY KEY,
  iso1 TEXT NOT NULL,
  script TEXT NULL,
  iso3 TEXT NOT NULL,
  macro TEXT NULL,
  name TEXT NOT NULL);
INSERT INTO Language VALUES ('af', 'af', null, 'afr', null, 'Afrikaans');
INSERT INTO Language VALUES ('agq', 'agq', null, 'agq', null, 'Aghem');
INSERT INTO Language VALUES ('ak', 'ak', null, 'aka', 'aka', 'Akan');
INSERT INTO Language VALUES ('am', 'am', null, 'amh', null, 'Amharic');
INSERT INTO Language VALUES ('ar', 'ar', null, 'ara', 'ara', 'Arabic');
INSERT INTO Language VALUES ('as', 'as', null, 'asm', null, 'Assamese');
INSERT INTO Language VALUES ('asa', 'asa', null, 'asa', null, 'Asu');
INSERT INTO Language VALUES ('ast', 'ast', null, 'ast', null, 'Asturian');
INSERT INTO Language VALUES ('az', 'az', null, 'aze', 'aze', 'Azerbaijani');
INSERT INTO Language VALUES ('az_Cyrl', 'az', 'Cyrl', 'aze', 'aze', 'Azerbaijani (Cyrillic)');
INSERT INTO Language VALUES ('az_Latn', 'az', null, 'aze', 'aze', 'Azerbaijani (Latin)');
INSERT INTO Language VALUES ('bas', 'bas', null, 'bas', null, 'Basaa');
INSERT INTO Language VALUES ('be', 'be', null, 'bel', null, 'Belarusian');
INSERT INTO Language VALUES ('bem', 'bem', null, 'bem', null, 'Bemba');
INSERT INTO Language VALUES ('bez', 'bez', null, 'bez', null, 'Bena');
INSERT INTO Language VALUES ('bg', 'bg', null, 'bul', null, 'Bulgarian');
INSERT INTO Language VALUES ('bm', 'bm', null, 'bam', null, 'Bambara');
INSERT INTO Language VALUES ('bn', 'bn', null, 'ben', null, 'Bangla');
INSERT INTO Language VALUES ('bo', 'bo', null, 'bod', null, 'Tibetan');
INSERT INTO Language VALUES ('br', 'br', null, 'bre', null, 'Breton');
INSERT INTO Language VALUES ('brx', 'brx', null, 'brx', null, 'Bodo');
INSERT INTO Language VALUES ('bs', 'bs', null, 'bos', 'hbs', 'Bosnian');
INSERT INTO Language VALUES ('bs_Cyrl', 'bs', 'Cyrl', 'bos', 'hbs', 'Bosnian (Cyrillic)');
INSERT INTO Language VALUES ('bs_Latn', 'bs', null, 'bos', 'hbs', 'Bosnian (Latin)');
INSERT INTO Language VALUES ('ca', 'ca', null, 'cat', null, 'Catalan');
INSERT INTO Language VALUES ('ccp', 'ccp', null, 'ccp', null, 'Chakma   extra');
INSERT INTO Language VALUES ('ce', 'ce', null, 'che', null, 'Chechen');
INSERT INTO Language VALUES ('cgg', 'cgg', null, 'cgg', null, 'Chiga');
INSERT INTO Language VALUES ('chr', 'chr', null, 'chr', null, 'Cherokee');
INSERT INTO Language VALUES ('ckb', 'ckb', null, 'ckb', 'kur', 'Central Kurdish');
INSERT INTO Language VALUES ('cs', 'cs', null, 'ces', null, 'Czech');
INSERT INTO Language VALUES ('cy', 'cy', null, 'cym', null, 'Welsh');
INSERT INTO Language VALUES ('da', 'da', null, 'dan', null, 'Danish');
INSERT INTO Language VALUES ('dav', 'dav', null, 'dav', null, 'Taita');
INSERT INTO Language VALUES ('de', 'de', null, 'deu', null, 'German');
INSERT INTO Language VALUES ('dje', 'dje', null, 'dje', null, 'Zarma');
INSERT INTO Language VALUES ('dsb', 'dsb', null, 'dsb', null, 'Lower Sorbian');
INSERT INTO Language VALUES ('dua', 'dua', null, 'dua', null, 'Duala');
INSERT INTO Language VALUES ('dyo', 'dyo', null, 'dyo', null, 'Jola-Fonyi');
INSERT INTO Language VALUES ('dz', 'dz', null, 'dzo', null, 'Dzongkha');
INSERT INTO Language VALUES ('ebu', 'ebu', null, 'ebu', null, 'Embu');
INSERT INTO Language VALUES ('ee', 'ee', null, 'ewe', null, 'Ewe');
INSERT INTO Language VALUES ('el', 'el', null, 'ell', null, 'Greek');
INSERT INTO Language VALUES ('en', 'en', null, 'eng', null, 'English');
INSERT INTO Language VALUES ('eo', 'eo', null, 'epo', null, 'Esperanto');
INSERT INTO Language VALUES ('es', 'es', null, 'spa', null, 'Spanish');
INSERT INTO Language VALUES ('et', 'et', null, 'est', 'est', 'Estonian');
INSERT INTO Language VALUES ('eu', 'eu', null, 'eus', null, 'Basque');
INSERT INTO Language VALUES ('ewo', 'ewo', null, 'ewo', null, 'Ewondo');
INSERT INTO Language VALUES ('fa', 'fa', null, 'fas', 'fas', 'Persian');
INSERT INTO Language VALUES ('ff', 'ff', null, 'ful', 'ful', 'Fulah');
INSERT INTO Language VALUES ('fi', 'fi', null, 'fin', null, 'Finnish');
INSERT INTO Language VALUES ('fil', 'fil', null, 'fil', null, 'Filipino');
INSERT INTO Language VALUES ('fo', 'fo', null, 'fao', null, 'Faroese');
INSERT INTO Language VALUES ('fr', 'fr', null, 'fra', null, 'French');
INSERT INTO Language VALUES ('fur', 'fur', null, 'fur', null, 'Friulian');
INSERT INTO Language VALUES ('fy', 'fy', null, 'fry', null, 'Western Frisian');
INSERT INTO Language VALUES ('ga', 'ga', null, 'gle', null, 'Irish');
INSERT INTO Language VALUES ('gd', 'gd', null, 'gla', null, 'Scottish Gaelic');
INSERT INTO Language VALUES ('gl', 'gl', null, 'glg', null, 'Galician');
INSERT INTO Language VALUES ('gsw', 'gsw', null, 'gsw', null, 'Swiss German');
INSERT INTO Language VALUES ('gu', 'gu', null, 'guj', null, 'Gujarati');
INSERT INTO Language VALUES ('guz', 'guz', null, 'guz', null, 'Gusii');
INSERT INTO Language VALUES ('gv', 'gv', null, 'glv', null, 'Manx');
INSERT INTO Language VALUES ('ha', 'ha', null, 'hau', null, 'Hausa');
INSERT INTO Language VALUES ('haw', 'haw', null, 'haw', null, 'Hawaiian');
INSERT INTO Language VALUES ('he', 'he', null, 'heb', null, 'Hebrew');
INSERT INTO Language VALUES ('hi', 'hi', null, 'hin', null, 'Hindi');
INSERT INTO Language VALUES ('hr', 'hr', null, 'hrv', 'hbs', 'Croatian');
INSERT INTO Language VALUES ('hsb', 'hsb', null, 'hsb', null, 'Upper Sorbian');
INSERT INTO Language VALUES ('hu', 'hu', null, 'hun', null, 'Hungarian');
INSERT INTO Language VALUES ('hy', 'hy', null, 'hye', null, 'Armenian');
INSERT INTO Language VALUES ('id', 'id', null, 'ind', 'msa', 'Indonesian');
INSERT INTO Language VALUES ('ig', 'ig', null, 'ibo', null, 'Igbo');
INSERT INTO Language VALUES ('ii', 'ii', null, 'iii', null, 'Sichuan Yi');
INSERT INTO Language VALUES ('is', 'is', null, 'isl', null, 'Icelandic');
INSERT INTO Language VALUES ('it', 'it', null, 'ita', null, 'Italian');
INSERT INTO Language VALUES ('iu', 'iu', null, 'iku', 'iku', 'Inuktitut');
INSERT INTO Language VALUES ('ja', 'ja', null, 'jpn', null, 'Japanese');
INSERT INTO Language VALUES ('jgo', 'jgo', null, 'jgo', null, 'Ngomba');
INSERT INTO Language VALUES ('jmc', 'jmc', null, 'jmc', null, 'Machame');
INSERT INTO Language VALUES ('ka', 'ka', null, 'kat', null, 'Georgian');
INSERT INTO Language VALUES ('kab', 'kab', null, 'kab', null, 'Kabyle');
INSERT INTO Language VALUES ('kam', 'kam', null, 'kam', null, 'Kamba');
INSERT INTO Language VALUES ('kde', 'kde', null, 'kde', null, 'Makonde');
INSERT INTO Language VALUES ('kea', 'kea', null, 'kea', null, 'Kabuverdianu');
INSERT INTO Language VALUES ('khq', 'khq', null, 'khq', null, 'Koyra Chiini');
INSERT INTO Language VALUES ('ki', 'ki', null, 'kik', null, 'Kikuyu');
INSERT INTO Language VALUES ('kk', 'kk', null, 'kaz', null, 'Kazakh');
INSERT INTO Language VALUES ('kkj', 'kkj', null, 'kkj', null, 'Kako');
INSERT INTO Language VALUES ('kl', 'kl', null, 'kal', null, 'Kalaallisut');
INSERT INTO Language VALUES ('kln', 'kln', null, 'kln', 'kln', 'Kalenjin');
INSERT INTO Language VALUES ('km', 'km', null, 'khm', null, 'Khmer');
INSERT INTO Language VALUES ('kn', 'kn', null, 'kan', null, 'Kannada');
INSERT INTO Language VALUES ('ko', 'ko', null, 'kor', null, 'Korean');
INSERT INTO Language VALUES ('kok', 'kok', null, 'kok', 'kok', 'Konkani');
INSERT INTO Language VALUES ('ks', 'ks', null, 'kas', null, 'Kashmiri');
INSERT INTO Language VALUES ('ksb', 'ksb', null, 'ksb', null, 'Shambala');
INSERT INTO Language VALUES ('ksf', 'ksf', null, 'ksf', null, 'Bafia');
INSERT INTO Language VALUES ('ksh', 'ksh', null, 'ksh', null, 'Colognian');
INSERT INTO Language VALUES ('kw', 'kw', null, 'cor', null, 'Cornish');
INSERT INTO Language VALUES ('ky', 'ky', null, 'kir', null, 'Kyrgyz');
INSERT INTO Language VALUES ('lag', 'lag', null, 'lag', null, 'Langi');
INSERT INTO Language VALUES ('lb', 'lb', null, 'ltz', null, 'Luxembourgish');
INSERT INTO Language VALUES ('lg', 'lg', null, 'lug', null, 'Ganda');
INSERT INTO Language VALUES ('lkt', 'lkt', null, 'lkt', null, 'Lakota');
INSERT INTO Language VALUES ('ln', 'ln', null, 'lin', null, 'Lingala');
INSERT INTO Language VALUES ('lo', 'lo', null, 'lao', null, 'Lao');
INSERT INTO Language VALUES ('lrc', 'lrc', null, 'lrc', null, 'Northern Luri');
INSERT INTO Language VALUES ('lt', 'lt', null, 'lit', null, 'Lithuanian');
INSERT INTO Language VALUES ('lu', 'lu', null, 'lub', null, 'Luba-Katanga');
INSERT INTO Language VALUES ('luo', 'luo', null, 'luo', null, 'Luo');
INSERT INTO Language VALUES ('luy', 'luy', null, 'luy', 'luy', 'Luyia');
INSERT INTO Language VALUES ('lv', 'lv', null, 'lav', 'lav', 'Latvian');
INSERT INTO Language VALUES ('mas', 'mas', null, 'mas', null, 'Masai');
INSERT INTO Language VALUES ('mer', 'mer', null, 'mer', null, 'Meru');
INSERT INTO Language VALUES ('mfe', 'mfe', null, 'mfe', null, 'Morisyen');
INSERT INTO Language VALUES ('mg', 'mg', null, 'mlg', 'mlg', 'Malagasy');
INSERT INTO Language VALUES ('mgh', 'mgh', null, 'mgh', null, 'Makhuwa-Meetto');
INSERT INTO Language VALUES ('mgo', 'mgo', null, 'mgo', null, 'Metaʼ');
INSERT INTO Language VALUES ('mk', 'mk', null, 'mkd', null, 'Macedonian');
INSERT INTO Language VALUES ('ml', 'ml', null, 'mal', null, 'Malayalam');
INSERT INTO Language VALUES ('mn', 'mn', null, 'mon', 'mon', 'Mongolian');
INSERT INTO Language VALUES ('mr', 'mr', null, 'mar', null, 'Marathi');
INSERT INTO Language VALUES ('ms', 'ms', null, 'msa', 'msa', 'Malay');
INSERT INTO Language VALUES ('ms_Arab', 'ms', 'Arab', 'msa', 'msa', 'Malay (Arabic)');
INSERT INTO Language VALUES ('mt', 'mt', null, 'mlt', null, 'Maltese');
INSERT INTO Language VALUES ('mua', 'mua', null, 'mua', null, 'Mundang');
INSERT INTO Language VALUES ('my', 'my', null, 'mya', null, 'Burmese');
INSERT INTO Language VALUES ('mzn', 'mzn', null, 'mzn', null, 'Mazanderani');
INSERT INTO Language VALUES ('naq', 'naq', null, 'naq', null, 'Nama');
INSERT INTO Language VALUES ('nb', 'nb', null, 'nob', 'nor', 'Norwegian Bokmål');
INSERT INTO Language VALUES ('nd', 'nd', null, 'nde', null, 'North Ndebele');
INSERT INTO Language VALUES ('nds', 'nds', null, 'nds', null, 'Low German');
INSERT INTO Language VALUES ('ne', 'ne', null, 'nep', 'nep', 'Nepali');
INSERT INTO Language VALUES ('nl', 'nl', null, 'nld', null, 'Dutch');
INSERT INTO Language VALUES ('nmg', 'nmg', null, 'nmg', null, 'Kwasio');
INSERT INTO Language VALUES ('nn', 'nn', null, 'nno', 'nor', 'Norwegian Nynorsk');
INSERT INTO Language VALUES ('nnh', 'nnh', null, 'nnh', null, 'Ngiemboon');
INSERT INTO Language VALUES ('nus', 'nus', null, 'nus', null, 'Nuer');
INSERT INTO Language VALUES ('nyn', 'nyn', null, 'nyn', null, 'Nyankole');
INSERT INTO Language VALUES ('om', 'om', null, 'orm', 'orm', 'Oromo');
INSERT INTO Language VALUES ('or', 'or', null, 'ori', 'ori', 'Odia');
INSERT INTO Language VALUES ('os', 'os', null, 'oss', null, 'Ossetic');
INSERT INTO Language VALUES ('pa', 'pa', null, 'pan', null, 'Punjabi');
INSERT INTO Language VALUES ('pa_Arab', 'pa', 'Arab', 'pan', null, 'Punjabi (Arabic)');
INSERT INTO Language VALUES ('pa_Guru', 'pa', null, 'pan', null, 'Punjabi (Gurmukhi)');
INSERT INTO Language VALUES ('pl', 'pl', null, 'pol', null, 'Polish');
INSERT INTO Language VALUES ('ps', 'ps', null, 'pus', 'pus', 'Pashto');
INSERT INTO Language VALUES ('pt', 'pt', null, 'por', null, 'Portuguese');
INSERT INTO Language VALUES ('qu', 'qu', null, 'que', 'que', 'Quechua');
INSERT INTO Language VALUES ('rm', 'rm', null, 'roh', null, 'Romansh');
INSERT INTO Language VALUES ('rn', 'rn', null, 'run', null, 'Rundi');
INSERT INTO Language VALUES ('ro', 'ro', null, 'ron', null, 'Romanian');
INSERT INTO Language VALUES ('rof', 'rof', null, 'rof', null, 'Rombo');
INSERT INTO Language VALUES ('ru', 'ru', null, 'rus', null, 'Russian');
INSERT INTO Language VALUES ('rw', 'rw', null, 'kin', null, 'Kinyarwanda');
INSERT INTO Language VALUES ('rwk', 'rwk', null, 'rwk', null, 'Rwa');
INSERT INTO Language VALUES ('sah', 'sah', null, 'sah', null, 'Sakha');
INSERT INTO Language VALUES ('saq', 'saq', null, 'saq', null, 'Samburu');
INSERT INTO Language VALUES ('sbp', 'sbp', null, 'sbp', null, 'Sangu');
INSERT INTO Language VALUES ('se', 'se', null, 'sme', null, 'Northern Sami');
INSERT INTO Language VALUES ('seh', 'seh', null, 'seh', null, 'Sena');
INSERT INTO Language VALUES ('ses', 'ses', null, 'ses', null, 'Koyraboro Senni');
INSERT INTO Language VALUES ('sg', 'sg', null, 'sag', null, 'Sango');
INSERT INTO Language VALUES ('shi', 'shi', null, 'shi', null, 'Tachelhit');
INSERT INTO Language VALUES ('shi_Latn', 'shi', null, 'shi', null, 'Tachelhit (Latin)');
INSERT INTO Language VALUES ('shi_Tfng', 'shi', 'Tfng', 'shi', null, 'Tachelhit (Tifinagh)');
INSERT INTO Language VALUES ('si', 'si', null, 'sin', null, 'Sinhala');
INSERT INTO Language VALUES ('sk', 'sk', null, 'slk', null, 'Slovak');
INSERT INTO Language VALUES ('sl', 'sl', null, 'slv', null, 'Slovenian');
INSERT INTO Language VALUES ('smn', 'smn', null, 'smn', null, 'Inari Sami');
INSERT INTO Language VALUES ('sn', 'sn', null, 'sna', null, 'Shona');
INSERT INTO Language VALUES ('so', 'so', null, 'som', null, 'Somali');
INSERT INTO Language VALUES ('sq', 'sq', null, 'sqi', 'sqi', 'Albanian');
INSERT INTO Language VALUES ('sr', 'sr', null, 'srp', 'hbs', 'Serbian');
INSERT INTO Language VALUES ('sr_Cyrl', 'sr', null, 'srp', 'hbs', 'Serbian (Cyrillic)');
INSERT INTO Language VALUES ('sr_Latn', 'sr', 'Latn', 'srp', 'hbs', 'Serbian (Latin)');
INSERT INTO Language VALUES ('sv', 'sv', null, 'swe', null, 'Swedish');
INSERT INTO Language VALUES ('sw', 'sw', null, 'swa', 'swa', 'Swahili');
INSERT INTO Language VALUES ('ta', 'ta', null, 'tam', null, 'Tamil');
INSERT INTO Language VALUES ('te', 'te', null, 'tel', null, 'Telugu');
INSERT INTO Language VALUES ('teo', 'teo', null, 'teo', null, 'Teso');
INSERT INTO Language VALUES ('tg', 'tg', null, 'tgk', null, 'Tajik');
INSERT INTO Language VALUES ('th', 'th', null, 'tha', null, 'Thai');
INSERT INTO Language VALUES ('ti', 'ti', null, 'tir', null, 'Tigrinya');
INSERT INTO Language VALUES ('tk', 'tk', null, 'tuk', null, 'Turkmen');
INSERT INTO Language VALUES ('to', 'to', null, 'ton', null, 'Tongan');
INSERT INTO Language VALUES ('tr', 'tr', null, 'tur', null, 'Turkish');
INSERT INTO Language VALUES ('tt', 'tt', null, 'tat', null, 'Tatar');
INSERT INTO Language VALUES ('twq', 'twq', null, 'twq', null, 'Tasawaq');
INSERT INTO Language VALUES ('tzm', 'tzm', null, 'tzm', null, 'Central Atlas Tamazight');
INSERT INTO Language VALUES ('ug', 'ug', null, 'uig', null, 'Uyghur');
INSERT INTO Language VALUES ('uk', 'uk', null, 'ukr', null, 'Ukrainian');
INSERT INTO Language VALUES ('ur', 'ur', null, 'urd', null, 'Urdu');
INSERT INTO Language VALUES ('uz', 'uz', null, 'uzb', 'uzb', 'Uzbek');
INSERT INTO Language VALUES ('uz_Arab', 'uz', 'Arab', 'uzb', 'uzb', 'Uzbek (Arabic)');
INSERT INTO Language VALUES ('uz_Cyrl', 'uz', null, 'uzb', 'uzb', 'Uzbek (Cyrillic)');
INSERT INTO Language VALUES ('uz_Latn', 'uz', 'Latn', 'uzb', 'uzb', 'Uzbek (Latin)');
INSERT INTO Language VALUES ('vai', 'vai', null, 'vai', null, 'Vai');
INSERT INTO Language VALUES ('vai_Latn', 'vai', 'Latn', 'vai', null, 'Vai (Latin)');
INSERT INTO Language VALUES ('vai_Vaii', 'vai', null, 'vai', null, 'Vai (Vai)');
INSERT INTO Language VALUES ('vi', 'vi', null, 'vie', null, 'Vietnamese');
INSERT INTO Language VALUES ('vun', 'vun', null, 'vun', null, 'Vunjo');
INSERT INTO Language VALUES ('wae', 'wae', null, 'wae', null, 'Walser');
INSERT INTO Language VALUES ('wo', 'wo', null, 'wol', null, 'Wolof');
INSERT INTO Language VALUES ('xog', 'xog', null, 'xog', null, 'Soga');
INSERT INTO Language VALUES ('yav', 'yav', null, 'yav', null, 'Yangben');
INSERT INTO Language VALUES ('yi', 'yi', null, 'yid', 'yid', 'Yiddish');
INSERT INTO Language VALUES ('yo', 'yo', null, 'yor', null, 'Yoruba');
INSERT INTO Language VALUES ('yue', 'yue', null, 'yue', 'zho', 'Cantonese');
INSERT INTO Language VALUES ('yue_Hans', 'yue', 'Hans', 'yue', 'zho', 'Cantonese (Simplified)');
INSERT INTO Language VALUES ('yue_Hant', 'yue', 'Hant', 'yue', 'zho', 'Cantonese (Traditional)');
INSERT INTO Language VALUES ('zgh', 'zgh', null, 'zgh', null, 'Standard Moroccan Tamazight');
INSERT INTO Language VALUES ('zh', 'zh', null, 'zho', 'zho', 'Chinese');
INSERT INTO Language VALUES ('zh_Hans', 'zh', 'Hans', 'zho', 'zho', 'Chinese (Simplified)');
INSERT INTO Language VALUES ('zh_Hant', 'zh', 'Hant', 'zho', 'zho', 'Chinese (Traditional)');
INSERT INTO Language VALUES ('zu', 'zu', null, 'zul', null, 'Zulu');
