DROP TABLE IF EXISTS Language;
CREATE TABLE Language (
  locale TEXT NOT NULL PRIMARY KEY,
  iso3 TEXT NOT NULL,
  macro TEXT NULL,
  name TEXT NOT NULL);
INSERT INTO Language VALUES ('af', 'afr', '', 'Afrikaans');
INSERT INTO Language VALUES ('agq', 'agq', '', 'Aghem');
INSERT INTO Language VALUES ('ak', 'aka', 'aka', 'Akan');
INSERT INTO Language VALUES ('am', 'amh', '', 'Amharic');
INSERT INTO Language VALUES ('ar', 'ara', 'ara', 'Arabic');
INSERT INTO Language VALUES ('as', 'asm', '', 'Assamese');
INSERT INTO Language VALUES ('asa', 'asa', '', 'Asu');
INSERT INTO Language VALUES ('ast', 'ast', '', 'Asturian');
INSERT INTO Language VALUES ('az', 'aze', 'aze', 'Azerbaijani');
INSERT INTO Language VALUES ('az_Cyrl', 'aze', 'aze', 'Azerbaijani (Cyrillic)');
INSERT INTO Language VALUES ('az_Latn', 'aze', 'aze', 'Azerbaijani (Latin)');
INSERT INTO Language VALUES ('bas', 'bas', '', 'Basaa');
INSERT INTO Language VALUES ('be', 'bel', '', 'Belarusian');
INSERT INTO Language VALUES ('bem', 'bem', '', 'Bemba');
INSERT INTO Language VALUES ('bez', 'bez', '', 'Bena');
INSERT INTO Language VALUES ('bg', 'bul', '', 'Bulgarian');
INSERT INTO Language VALUES ('bm', 'bam', '', 'Bambara');
INSERT INTO Language VALUES ('bn', 'ben', '', 'Bangla');
INSERT INTO Language VALUES ('bo', 'bod', '', 'Tibetan');
INSERT INTO Language VALUES ('br', 'bre', '', 'Breton');
INSERT INTO Language VALUES ('brx', 'brx', '', 'Bodo');
INSERT INTO Language VALUES ('bs', 'bos', 'hbs', 'Bosnian');
INSERT INTO Language VALUES ('bs_Cyrl', 'bos', 'hbs', 'Bosnian (Cyrillic)');
INSERT INTO Language VALUES ('bs_Latn', 'bos', 'hbs', 'Bosnian (Latin)');
INSERT INTO Language VALUES ('ca', 'cat', '', 'Catalan');
INSERT INTO Language VALUES ('ccp', 'ccp', '', 'Chakma   extra');
INSERT INTO Language VALUES ('ce', 'che', '', 'Chechen');
INSERT INTO Language VALUES ('cgg', 'cgg', '', 'Chiga');
INSERT INTO Language VALUES ('chr', 'chr', '', 'Cherokee');
INSERT INTO Language VALUES ('ckb', 'ckb', 'kur', 'Central Kurdish');
INSERT INTO Language VALUES ('cs', 'ces', '', 'Czech');
INSERT INTO Language VALUES ('cy', 'cym', '', 'Welsh');
INSERT INTO Language VALUES ('da', 'dan', '', 'Danish');
INSERT INTO Language VALUES ('dav', 'dav', '', 'Taita');
INSERT INTO Language VALUES ('de', 'deu', '', 'German');
INSERT INTO Language VALUES ('dje', 'dje', '', 'Zarma');
INSERT INTO Language VALUES ('dsb', 'dsb', '', 'Lower Sorbian');
INSERT INTO Language VALUES ('dua', 'dua', '', 'Duala');
INSERT INTO Language VALUES ('dyo', 'dyo', '', 'Jola-Fonyi');
INSERT INTO Language VALUES ('dz', 'dzo', '', 'Dzongkha');
INSERT INTO Language VALUES ('ebu', 'ebu', '', 'Embu');
INSERT INTO Language VALUES ('ee', 'ewe', '', 'Ewe');
INSERT INTO Language VALUES ('el', 'ell', '', 'Greek');
INSERT INTO Language VALUES ('en', 'eng', '', 'English');
INSERT INTO Language VALUES ('eo', 'epo', '', 'Esperanto');
INSERT INTO Language VALUES ('es', 'spa', '', 'Spanish');
INSERT INTO Language VALUES ('et', 'est', 'est', 'Estonian');
INSERT INTO Language VALUES ('eu', 'eus', '', 'Basque');
INSERT INTO Language VALUES ('ewo', 'ewo', '', 'Ewondo');
INSERT INTO Language VALUES ('fa', 'fas', 'fas', 'Persian');
INSERT INTO Language VALUES ('ff', 'ful', 'ful', 'Fulah');
INSERT INTO Language VALUES ('fi', 'fin', '', 'Finnish');
INSERT INTO Language VALUES ('fil', 'fil', '', 'Filipino');
INSERT INTO Language VALUES ('fo', 'fao', '', 'Faroese');
INSERT INTO Language VALUES ('fr', 'fra', '', 'French');
INSERT INTO Language VALUES ('fur', 'fur', '', 'Friulian');
INSERT INTO Language VALUES ('fy', 'fry', '', 'Western Frisian');
INSERT INTO Language VALUES ('ga', 'gle', '', 'Irish');
INSERT INTO Language VALUES ('gd', 'gla', '', 'Scottish Gaelic');
INSERT INTO Language VALUES ('gl', 'glg', '', 'Galician');
INSERT INTO Language VALUES ('gsw', 'gsw', '', 'Swiss German');
INSERT INTO Language VALUES ('gu', 'guj', '', 'Gujarati');
INSERT INTO Language VALUES ('guz', 'guz', '', 'Gusii');
INSERT INTO Language VALUES ('gv', 'glv', '', 'Manx');
INSERT INTO Language VALUES ('ha', 'hau', '', 'Hausa');
INSERT INTO Language VALUES ('haw', 'haw', '', 'Hawaiian');
INSERT INTO Language VALUES ('he', 'heb', '', 'Hebrew');
INSERT INTO Language VALUES ('hi', 'hin', '', 'Hindi');
INSERT INTO Language VALUES ('hr', 'hrv', 'hbs', 'Croatian');
INSERT INTO Language VALUES ('hsb', 'hsb', '', 'Upper Sorbian');
INSERT INTO Language VALUES ('hu', 'hun', '', 'Hungarian');
INSERT INTO Language VALUES ('hy', 'hye', '', 'Armenian');
INSERT INTO Language VALUES ('id', 'ind', 'msa', 'Indonesian');
INSERT INTO Language VALUES ('ig', 'ibo', '', 'Igbo');
INSERT INTO Language VALUES ('ii', 'iii', '', 'Sichuan Yi');
INSERT INTO Language VALUES ('is', 'isl', '', 'Icelandic');
INSERT INTO Language VALUES ('it', 'ita', '', 'Italian');
INSERT INTO Language VALUES ('iu', 'iku', 'iku', 'Inuktitut');
INSERT INTO Language VALUES ('ja', 'jpn', '', 'Japanese');
INSERT INTO Language VALUES ('jgo', 'jgo', '', 'Ngomba');
INSERT INTO Language VALUES ('jmc', 'jmc', '', 'Machame');
INSERT INTO Language VALUES ('ka', 'kat', '', 'Georgian');
INSERT INTO Language VALUES ('kab', 'kab', '', 'Kabyle');
INSERT INTO Language VALUES ('kam', 'kam', '', 'Kamba');
INSERT INTO Language VALUES ('kde', 'kde', '', 'Makonde');
INSERT INTO Language VALUES ('kea', 'kea', '', 'Kabuverdianu');
INSERT INTO Language VALUES ('khq', 'khq', '', 'Koyra Chiini');
INSERT INTO Language VALUES ('ki', 'kik', '', 'Kikuyu');
INSERT INTO Language VALUES ('kk', 'kaz', '', 'Kazakh');
INSERT INTO Language VALUES ('kkj', 'kkj', '', 'Kako');
INSERT INTO Language VALUES ('kl', 'kal', '', 'Kalaallisut');
INSERT INTO Language VALUES ('kln', 'kln', 'kln', 'Kalenjin');
INSERT INTO Language VALUES ('km', 'khm', '', 'Khmer');
INSERT INTO Language VALUES ('kn', 'kan', '', 'Kannada');
INSERT INTO Language VALUES ('ko', 'kor', '', 'Korean');
INSERT INTO Language VALUES ('kok', 'kok', 'kok', 'Konkani');
INSERT INTO Language VALUES ('ks', 'kas', '', 'Kashmiri');
INSERT INTO Language VALUES ('ksb', 'ksb', '', 'Shambala');
INSERT INTO Language VALUES ('ksf', 'ksf', '', 'Bafia');
INSERT INTO Language VALUES ('ksh', 'ksh', '', 'Colognian');
INSERT INTO Language VALUES ('kw', 'cor', '', 'Cornish');
INSERT INTO Language VALUES ('ky', 'kir', '', 'Kyrgyz');
INSERT INTO Language VALUES ('lag', 'lag', '', 'Langi');
INSERT INTO Language VALUES ('lb', 'ltz', '', 'Luxembourgish');
INSERT INTO Language VALUES ('lg', 'lug', '', 'Ganda');
INSERT INTO Language VALUES ('lkt', 'lkt', '', 'Lakota');
INSERT INTO Language VALUES ('ln', 'lin', '', 'Lingala');
INSERT INTO Language VALUES ('lo', 'lao', '', 'Lao');
INSERT INTO Language VALUES ('lrc', 'lrc', '', 'Northern Luri');
INSERT INTO Language VALUES ('lt', 'lit', '', 'Lithuanian');
INSERT INTO Language VALUES ('lu', 'lub', '', 'Luba-Katanga');
INSERT INTO Language VALUES ('luo', 'luo', '', 'Luo');
INSERT INTO Language VALUES ('luy', 'luy', 'luy', 'Luyia');
INSERT INTO Language VALUES ('lv', 'lav', 'lav', 'Latvian');
INSERT INTO Language VALUES ('mas', 'mas', '', 'Masai');
INSERT INTO Language VALUES ('mer', 'mer', '', 'Meru');
INSERT INTO Language VALUES ('mfe', 'mfe', '', 'Morisyen');
INSERT INTO Language VALUES ('mg', 'mlg', 'mlg', 'Malagasy');
INSERT INTO Language VALUES ('mgh', 'mgh', '', 'Makhuwa-Meetto');
INSERT INTO Language VALUES ('mgo', 'mgo', '', 'Metaʼ');
INSERT INTO Language VALUES ('mk', 'mkd', '', 'Macedonian');
INSERT INTO Language VALUES ('ml', 'mal', '', 'Malayalam');
INSERT INTO Language VALUES ('mn', 'mon', 'mon', 'Mongolian');
INSERT INTO Language VALUES ('mr', 'mar', '', 'Marathi');
INSERT INTO Language VALUES ('ms', 'msa', 'msa', 'Malay');
INSERT INTO Language VALUES ('ms_Arab', 'msa', 'msa', 'Malay (Arabic)');
INSERT INTO Language VALUES ('mt', 'mlt', '', 'Maltese');
INSERT INTO Language VALUES ('mua', 'mua', '', 'Mundang');
INSERT INTO Language VALUES ('my', 'mya', '', 'Burmese');
INSERT INTO Language VALUES ('mzn', 'mzn', '', 'Mazanderani');
INSERT INTO Language VALUES ('naq', 'naq', '', 'Nama');
INSERT INTO Language VALUES ('nb', 'nob', 'nor', 'Norwegian Bokmål');
INSERT INTO Language VALUES ('nd', 'nde', '', 'North Ndebele');
INSERT INTO Language VALUES ('nds', 'nds', '', 'Low German');
INSERT INTO Language VALUES ('ne', 'nep', 'nep', 'Nepali');
INSERT INTO Language VALUES ('nl', 'nld', '', 'Dutch');
INSERT INTO Language VALUES ('nmg', 'nmg', '', 'Kwasio');
INSERT INTO Language VALUES ('nn', 'nno', 'nor', 'Norwegian Nynorsk');
INSERT INTO Language VALUES ('nnh', 'nnh', '', 'Ngiemboon');
INSERT INTO Language VALUES ('nus', 'nus', '', 'Nuer');
INSERT INTO Language VALUES ('nyn', 'nyn', '', 'Nyankole');
INSERT INTO Language VALUES ('om', 'orm', 'orm', 'Oromo');
INSERT INTO Language VALUES ('or', 'ori', 'ori', 'Odia');
INSERT INTO Language VALUES ('os', 'oss', '', 'Ossetic');
INSERT INTO Language VALUES ('pa', 'pan', '', 'Punjabi');
INSERT INTO Language VALUES ('pa_Arab', 'pan', '', 'Punjabi (Arabic)');
INSERT INTO Language VALUES ('pa_Guru', 'pan', '', 'Punjabi (Gurmukhi)');
INSERT INTO Language VALUES ('pl', 'pol', '', 'Polish');
INSERT INTO Language VALUES ('ps', 'pus', 'pus', 'Pashto');
INSERT INTO Language VALUES ('pt', 'por', '', 'Portuguese');
INSERT INTO Language VALUES ('qu', 'que', 'que', 'Quechua');
INSERT INTO Language VALUES ('rm', 'roh', '', 'Romansh');
INSERT INTO Language VALUES ('rn', 'run', '', 'Rundi');
INSERT INTO Language VALUES ('ro', 'ron', '', 'Romanian');
INSERT INTO Language VALUES ('rof', 'rof', '', 'Rombo');
INSERT INTO Language VALUES ('ru', 'rus', '', 'Russian');
INSERT INTO Language VALUES ('rw', 'kin', '', 'Kinyarwanda');
INSERT INTO Language VALUES ('rwk', 'rwk', '', 'Rwa');
INSERT INTO Language VALUES ('sah', 'sah', '', 'Sakha');
INSERT INTO Language VALUES ('saq', 'saq', '', 'Samburu');
INSERT INTO Language VALUES ('sbp', 'sbp', '', 'Sangu');
INSERT INTO Language VALUES ('se', 'sme', '', 'Northern Sami');
INSERT INTO Language VALUES ('seh', 'seh', '', 'Sena');
INSERT INTO Language VALUES ('ses', 'ses', '', 'Koyraboro Senni');
INSERT INTO Language VALUES ('sg', 'sag', '', 'Sango');
INSERT INTO Language VALUES ('shi', 'shi', '', 'Tachelhit');
INSERT INTO Language VALUES ('shi_Latn', 'shi', '', 'Tachelhit (Latin)');
INSERT INTO Language VALUES ('shi_Tfng', 'shi', '', 'Tachelhit (Tifinagh)');
INSERT INTO Language VALUES ('si', 'sin', '', 'Sinhala');
INSERT INTO Language VALUES ('sk', 'slk', '', 'Slovak');
INSERT INTO Language VALUES ('sl', 'slv', '', 'Slovenian');
INSERT INTO Language VALUES ('smn', 'smn', '', 'Inari Sami');
INSERT INTO Language VALUES ('sn', 'sna', '', 'Shona');
INSERT INTO Language VALUES ('so', 'som', '', 'Somali');
INSERT INTO Language VALUES ('sq', 'sqi', 'sqi', 'Albanian');
INSERT INTO Language VALUES ('sr', 'srp', 'hbs', 'Serbian');
INSERT INTO Language VALUES ('sr_Cyrl', 'srp', 'hbs', 'Serbian (Cyrillic)');
INSERT INTO Language VALUES ('sr_Latn', 'srp', 'hbs', 'Serbian (Latin)');
INSERT INTO Language VALUES ('sv', 'swe', '', 'Swedish');
INSERT INTO Language VALUES ('sw', 'swa', 'swa', 'Swahili');
INSERT INTO Language VALUES ('ta', 'tam', '', 'Tamil');
INSERT INTO Language VALUES ('te', 'tel', '', 'Telugu');
INSERT INTO Language VALUES ('teo', 'teo', '', 'Teso');
INSERT INTO Language VALUES ('tg', 'tgk', '', 'Tajik');
INSERT INTO Language VALUES ('th', 'tha', '', 'Thai');
INSERT INTO Language VALUES ('ti', 'tir', '', 'Tigrinya');
INSERT INTO Language VALUES ('tk', 'tuk', '', 'Turkmen');
INSERT INTO Language VALUES ('to', 'ton', '', 'Tongan');
INSERT INTO Language VALUES ('tr', 'tur', '', 'Turkish');
INSERT INTO Language VALUES ('tt', 'tat', '', 'Tatar');
INSERT INTO Language VALUES ('twq', 'twq', '', 'Tasawaq');
INSERT INTO Language VALUES ('tzm', 'tzm', '', 'Central Atlas Tamazight');
INSERT INTO Language VALUES ('ug', 'uig', '', 'Uyghur');
INSERT INTO Language VALUES ('uk', 'ukr', '', 'Ukrainian');
INSERT INTO Language VALUES ('ur', 'urd', '', 'Urdu');
INSERT INTO Language VALUES ('uz', 'uzb', 'uzb', 'Uzbek');
INSERT INTO Language VALUES ('uz_Arab', 'uzb', 'uzb', 'Uzbek (Arabic)');
INSERT INTO Language VALUES ('uz_Cyrl', 'uzb', 'uzb', 'Uzbek (Cyrillic)');
INSERT INTO Language VALUES ('uz_Latn', 'uzb', 'uzb', 'Uzbek (Latin)');
INSERT INTO Language VALUES ('vai', 'vai', '', 'Vai');
INSERT INTO Language VALUES ('vai_Latn', 'vai', '', 'Vai (Latin)');
INSERT INTO Language VALUES ('vai_Vaii', 'vai', '', 'Vai (Vai)');
INSERT INTO Language VALUES ('vi', 'vie', '', 'Vietnamese');
INSERT INTO Language VALUES ('vun', 'vun', '', 'Vunjo');
INSERT INTO Language VALUES ('wae', 'wae', '', 'Walser');
INSERT INTO Language VALUES ('wo', 'wol', '', 'Wolof');
INSERT INTO Language VALUES ('xog', 'xog', '', 'Soga');
INSERT INTO Language VALUES ('yav', 'yav', '', 'Yangben');
INSERT INTO Language VALUES ('yi', 'yid', 'yid', 'Yiddish');
INSERT INTO Language VALUES ('yo', 'yor', '', 'Yoruba');
INSERT INTO Language VALUES ('yue', 'yue', 'zho', 'Cantonese');
INSERT INTO Language VALUES ('yue_Hans', 'yue', 'zho', 'Cantonese (Simplified)');
INSERT INTO Language VALUES ('yue_Hant', 'yue', 'zho', 'Cantonese (Traditional)');
INSERT INTO Language VALUES ('zgh', 'zgh', '', 'Standard Moroccan Tamazight');
INSERT INTO Language VALUES ('zh', 'zho', 'zho', 'Chinese');
INSERT INTO Language VALUES ('zh_Hans', 'zho', 'zho', 'Chinese (Simplified)');
INSERT INTO Language VALUES ('zh_Hant', 'zho', 'zho', 'Chinese (Traditional)');
INSERT INTO Language VALUES ('zu', 'zul', '', 'Zulu');
