DROP TABLE IF EXISTS Video;

CREATE TABLE Video (
	languageId TEXT NOT NULL,
	mediaId TEXT NOT NULL,
	silCode TEXT NOT NULL,
	langCode TEXT NOT NULL,
	title TEXT NOT NULL,
	lengthMS INT NOT NULL,
	HLS_URL TEXT NOT NULL,
	MP4_1080 TEXT NULL,
	MP4_720 TEXT NULL,
	MP4_540 TEXT NULL,
	MP4_360 TEXT NULL,
	longDescription TEXT NULL,
	PRIMARY KEY (languageId, mediaId)
);
CREATE INDEX Video_langCode ON Video (langCode);
